version: '3.8'
services:
  somu.api:
    image: ${DOCKER_REGISTRY-}somubackend
    build:
      context: .
      dockerfile: ./src/Somu.Backend/Dockerfile
    ports:
      - 5000:5000
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://somu.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://somu.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      somu.postgres:
        condition: service_healthy
  
  somu.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: somu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d somu" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  
  somu.seq:
    image: datalust/seq:2024.3 # or latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341

  somu.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
